#!/bin/sh
#
# Automatically upgrade Homebrew software.
#
# shellcheck shell=bash

if [ -r "$HOME/.zshrc" ]; then
	source "$HOME/.zshrc"
fi

if sh -c 'for verb in update upgrade cleanup; do brew $verb; done'; then
	message=""
	subtitle="completed successfully"
else
	message="Check Console.app for more details"
	subtitle="failed"
	sound="-sound"
fi
terminal-notifier "$sound" \
    -title "Brew Autoupdate" -message "$message" -subtitle "$subtitle" \
    -group "brew_autoupdate"
