#!/bin/sh
#
# Automatically upgrade Homebrew software.

for rc in .zshrc; do
	[ -e "$HOME/$rc" ] && . "$HOME/$rc"
done

if out=$(for verb in update upgrade cleanup; do brew $verb; done); then
	message=""
	subtitle="completed successfully"
else
	message="Check Console.app for more details"
	subtitle="failed"
	sound="-sound"
fi
terminal-notifier $sound \
    -title "Brew Autoupdate" -message "$message" -subtitle "$subtitle" \
    -group "brew_autoupdate"
